### ISSUE TITLE
Is there any document or helps to migrate from drf to django-ninja?

### ISSUE THREAD

**Issue by quroom** [vitalik/django-ninja#492]
It is not related to issue.
I am really thanksful to the founder of django-ninja
I was shocked it's really fast and easy and simplified comparing DRF
So I choosed to use django-ninja + ninja-extra to my new project.
But I already made some projects with drf  so nowadays I want to migrate all project from DRF to django-ninja , improving performance also simplify code structures.

Is there any tutorials or examples to acheive that? or supposed to make it?

**Comment by ihelmer07** [comment]
I don't know of any documentation however question - 
The biggest gap I've encountered with Django Ninja is the ability to POST/PUT m2m fields, which we do a lot of.

It looks that I have to custom write the functions to handle that which is a HUGE pain.

Do you know of how to deal with the POST/PUT of M2M fields?

**Comment by vitalik** [comment]
@ihelmer07 

Could you show some example where you write custom functions ?

**Comment by ihelmer07** [comment]
@vitalik 

Disclaimer - I may be missing something fundamental about django-ninja so please let me know if I'm wrong.

I've created a github example repo that shows the error [click here](https://github.com/ihelmer07/django-ninja-test)

For models with M2M relations, coming from DRF - one can post payloads such as `{"city_id": 1, "people": [2, 3, 4], "name": "Party People"}` where the `ints` are the `id` of the respective models and they will successfully create that object.

Please look at the [example repo](https://github.com/ihelmer07/django-ninja-test) that shows an apples to apples comparison for POSTing. I can update it with PUT if needed.

**Comment by vitalik** [comment]
@ihelmer07 

I assume you talke about this method:
```Python
@api.post("/order")
def create_order(request, payload: OrderPostSchema):
    """
    gives "AttributeError: 'int' object has no attribute 'pk'" when POSTing a payload that looks like:
    d = {"city_id": 1, "name": [2, 3, 4]}
    when those pks are known to exist.
    """
    obj = Order.objects.create(**payload.dict())
    return {"id": obj.id}
```

this is just the way django works - you cannot pass the integers for m2m - need to query it:


```Python
@api.post("/order")
def create_order(request, payload: OrderPostSchema):
    data = paylaod.dict()
    names = data.pop('name')
    obj = Order.objects.create(**data) 
    obj.name.add(*names)
    return {"id": obj.id}
```

**Comment by ihelmer07** [comment]
@vitalik - what you say makes sense however it is still failing with `AttributedError: 'int' object has no attribute 'pk'`

**Comment by ihelmer07** [comment]
@vitalik friendly ping. This is the 1 thing that prevents my team from transitioning to 100% django-ninja so any help is very appreciated!

**Comment by quroom** [comment]
@ihelmer07 But if there is some problem with ModelSchema.
I tested with your code but somehow M2M field is not passed with object. it is just id.
That's why it happened. 

It's not real solution. 
You can declare each schema. It can be more complex than using ModelSchema.
But I am sure it can fix your problem.

https://django-ninja.rest-framework.com/tutorial/response-schema/

You can set your own Inschema to avoid error.

**Comment by vitalik** [comment]
Hi @ihelmer07 @quroom 

so there is a bug in Manytomany fields - now it should work in pyalodas ( fixed in version 0.19.1)

**Comment by quroom** [comment]
> Hi @ihelmer07 @quroom 
> 
> so there is a bug in Manytomany fields - now it should work in pyalodas ( fixed in version 0.19.1)

Someday when I more understand django ninja, I hope to make pr. 

I am really thanksful your great work.
